### ISSUE TITLE
Dynamic class loading

### ISSUE THREAD

**Issue by akondasif** [thomasletsch/moserp#1]
Greetings, 

We are researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of dynamic class loading. [OWASP](https://rules.sonarsource.com/java/tag/owasp/RSPEC-2658)  says "Dynamically loaded classes could contain malicious code executed by a static class initializer i.e. you wouldn't even have to instantiate or explicitly invoke methods on such classes to be vulnerable to an attack."

Hopefully, you agree and will fix it.

Source: https://github.com/thomasletsch/moserp/blob/master/backend/common/common-base/src/main/java/org/moserp/RestConfiguration.java

**Comment by thomasletsch** [comment]
Yes, you are probably right :-) 
Since I do not further develop this software any more, it won't get fixed.
